/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movie_libary;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import movies.beans.*;

/**
 *
 * @author jacobwahlstrom
 */
public class MyMoviesUI extends javax.swing.JFrame {

    /**
     * Creates new form MyMoviesUI
     */
    public MyMoviesUI() {
        initComponents();
        updateMyMovies();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTtfSearchMovie = new javax.swing.JTextField();
        jBtnRemoveMovie = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListMovies = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextMPlot = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLPlaytime = new javax.swing.JLabel();
        jLRating = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTtpMoviePlot = new javax.swing.JTextPane();
        jLabelPlot = new javax.swing.JLabel();
        jBtnAddMovie = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jSpinnerMovieRating = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jTtFLink = new javax.swing.JTextField();
        jBIMDb = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtpAddTitle = new javax.swing.JTextPane();
        jPanel5 = new javax.swing.JPanel();
        jLabelTime = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTtpMovieTime = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneMain.setBackground(new java.awt.Color(230, 239, 233));

        jPanel1.setBackground(new java.awt.Color(230, 239, 233));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        jPanel7.setBackground(new java.awt.Color(230, 239, 233));

        jTtfSearchMovie.setEditable(false);
        jTtfSearchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtfSearchMovieActionPerformed(evt);
            }
        });

        jBtnRemoveMovie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnRemoveMovie.setText("Remove Movie");
        jBtnRemoveMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnRemoveMovieMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTtfSearchMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jBtnRemoveMovie)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtfSearchMovie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRemoveMovie))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("My Movie List");

        jListMovies.setBackground(new java.awt.Color(230, 239, 233));
        jListMovies.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jListMovies.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListMovies.setSelectionBackground(new java.awt.Color(185, 227, 198));
        jListMovies.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListMoviesMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(jListMovies);

        jTextMPlot.setEditable(false);
        jTextMPlot.setBackground(new java.awt.Color(230, 239, 233));
        jTextMPlot.setColumns(20);
        jTextMPlot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextMPlot.setLineWrap(true);
        jTextMPlot.setRows(5);
        jTextMPlot.setWrapStyleWord(true);
        jTextMPlot.setBorder(null);
        jTextMPlot.setMaximumSize(new java.awt.Dimension(200, 2147483647));
        jScrollPane6.setViewportView(jTextMPlot);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Plot");

        jLPlaytime.setBackground(new java.awt.Color(0, 0, 0));
        jLPlaytime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLPlaytime.setText("Time");

        jLRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLRating.setText("Rating");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(84, 84, 84)
                                .addComponent(jLPlaytime, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLRating))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLPlaytime, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLRating))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPaneMain.addTab("View movies", jPanel1);

        jPanel2.setBackground(new java.awt.Color(230, 239, 233));

        jPanel3.setBackground(new java.awt.Color(230, 239, 233));

        jTtpMoviePlot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(jTtpMoviePlot);

        jLabelPlot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPlot.setText("Plot");

        jBtnAddMovie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBtnAddMovie.setText("Add Move");
        jBtnAddMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAddMovieMouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(230, 239, 233));

        jSpinnerMovieRating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jSpinnerMovieRating.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Rating");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinnerMovieRating)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinnerMovieRating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTtFLink.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTtFLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTtFLinkActionPerformed(evt);
            }
        });

        jBIMDb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jBIMDb.setText("Get movie from IMDb");
        jBIMDb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBIMDbMousePressed(evt);
            }
        });
        jBIMDb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBIMDbActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("IMDb Link ");

        jLabel5.setText("The Link should look like this: http://www.imdb.com/title/tt0111161/");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTtFLink)
                                    .addComponent(jBIMDb, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(167, 167, 167))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelPlot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(187, 187, 187))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jBtnAddMovie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnAddMovie)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTtFLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBIMDb)
                .addGap(36, 36, 36))
        );

        jPanel4.setBackground(new java.awt.Color(230, 239, 233));

        jLabelTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTitle.setText("Title");

        jTtpAddTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(jTtpAddTitle);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(181, 181, 181))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(230, 239, 233));

        jLabelTime.setBackground(new java.awt.Color(230, 239, 233));
        jLabelTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTime.setText("Time / Duration");

        jTtpMovieTime.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jScrollPane3.setViewportView(jTtpMovieTime);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabelTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(72, 72, 72))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(187, 187, 187))
        );

        jTabbedPaneMain.addTab("Add movie", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTtfSearchMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtfSearchMovieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtfSearchMovieActionPerformed

    private void jBtnAddMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAddMovieMouseClicked
        // TODO add your handling code here:
        if (jTtpAddTitle.getText().isEmpty() == false
                && jTtpMoviePlot.getText().isEmpty() == false
                && jTtpMovieTime.getText().isEmpty() == false) {
            System.out.println("add Movie");

            ProductBean productBean = new ProductBean();
            String title = jTtpAddTitle.getText();
            String plot = jTtpMoviePlot.getText();
            int time = Integer.parseInt(jTtpMovieTime.getText());
            int rating = jSpinnerMovieRating.getComponentCount();

            try {
                productBean.postMovie(title, plot, time, rating);
                updateMyMovies();        
                jTabbedPaneMain.setSelectedIndex(0);

            } catch (SQLException ex) {
                Logger.getLogger(MyMoviesUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, " DU måste fylla i alla fäten utom betyg");
        }
        updateMyMovies();
    }//GEN-LAST:event_jBtnAddMovieMouseClicked

    private void jTtFLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTtFLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtFLinkActionPerformed

    private void jBIMDbMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBIMDbMousePressed
        // TODO add your handling code here:
        if (jTtFLink.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Du måste fylla i en länk");
        } else {
            String link = jTtFLink.getText();
            ProductBean productbean = new ProductBean();
            try {
                productbean.postMovieScrape(link);

                updateMyMovies();
                jTabbedPaneMain.setSelectedIndex(0);
                jTtFLink.setText("");
            } catch (SQLException ex) {
                Logger.getLogger(MyMoviesUI.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_jBIMDbMousePressed

    private void jBIMDbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBIMDbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBIMDbActionPerformed

    private void jBtnRemoveMovieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRemoveMovieMousePressed
        // TODO add your handling code here:

        String title = jListMovies.getSelectedValue();
        System.out.println(jListMovies.getSelectedIndex());
        System.out.println(title);
        if (title != null) {

            int id = myMovies.getMovieID(title);

            ProductBean productBean = new ProductBean();
            try {
                productBean.removeMovie(id);
                myMovies.removeMovie(title);

            } catch (SQLException ex) {
                Logger.getLogger(MyMoviesUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Du måste välja en film att ta bort");
        }
        updateMyMovies();
    }//GEN-LAST:event_jBtnRemoveMovieMousePressed

    private void jListMoviesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMoviesMousePressed
        // TODO add your handling code here:

        String title = jListMovies.getSelectedValue();
        String plot = myMovies.getMoviePlot(title);
        if (plot == "Not found") {
            JOptionPane.showMessageDialog(rootPane, "Some thing happend, what did you do? How did we come to this?");
        }
        int time = myMovies.getMovieTime(title);
        int rating = myMovies.getMovieRatingOf(title);
        jTextMPlot.setText(title + "\n" + plot);
        jLPlaytime.setText(String.valueOf(time) + " min");
        jLRating.setText("Rating " + rating);
    }//GEN-LAST:event_jListMoviesMousePressed

    /**
     * @param args the command line arguments
     */
    public static MyMovies myMovies = new MyMovies();

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyMoviesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyMoviesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyMoviesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyMoviesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyMoviesUI().setVisible(true);
            }
        });
    }

    public void updateMyMovies() {
        ProductBean productBean = new ProductBean();

        try {
            myMovies = productBean.getMoviesFromDataBase();
        } catch (SQLException ex) {
            Logger.getLogger(MyMoviesUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        //Start of setign the list
        DefaultListModel listModel = new DefaultListModel();
        String toAdd = "";
        for (int i = 0; i < myMovies.getNrOfMovies(); i++) {
            toAdd = myMovies.getMovieTitleAt(i);
            listModel.addElement(toAdd);

        }
        System.out.println("Succes update Movie");
        //cealrar den gammla listan
        jListMovies.clearSelection();
        jListMovies.setModel(listModel);
        //End
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBIMDb;
    private javax.swing.JButton jBtnAddMovie;
    private javax.swing.JButton jBtnRemoveMovie;
    private javax.swing.JLabel jLPlaytime;
    private javax.swing.JLabel jLRating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelPlot;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JList<String> jListMovies;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinnerMovieRating;
    private javax.swing.JTabbedPane jTabbedPaneMain;
    private javax.swing.JTextArea jTextMPlot;
    private javax.swing.JTextField jTtFLink;
    private javax.swing.JTextField jTtfSearchMovie;
    private javax.swing.JTextPane jTtpAddTitle;
    private javax.swing.JTextPane jTtpMoviePlot;
    private javax.swing.JTextPane jTtpMovieTime;
    // End of variables declaration//GEN-END:variables

}
